### ISSUE TITLE
JS file missing from .src

### ISSUE THREAD

**Issue by PaulScotchford** [q2g/q2g-ext-alternatestates#17]
Hi, Happy New Year; I have downloaded and unzipped the extension as per the instructions, however the Qlik System Engine log file shows the below error, thus rendering desktop use for this extension failing.

Log Entry ... The system cannot find the file specified: "D:\Users\Jonesps\Documents\Qlik\Sense\Extensions\q2g-ext-alternatestates-master\q2g-ext-alternatestates-master\src/q2g-ext-altStateExtension.js"

The Preview.png file appears to be missing too.

Thanks Paul

**Comment by PaulScotchford** [comment]
It appears this file src/q2g-ext-altStateExtension is saved as a .ts, edit this and re-save as a .js instead , thus the file is now found. Still seems to be another issue in the desktop, so I will investigate this and log a comment/issue

**Comment by PaulScotchford** [comment]
QlikSense Desktop November 2017 edition : I can see the Alternate States object, however when dragging it to the sheet it does not offer any other options to set it up for use except a title.

It sure would be nice to get this sorted out as my user really wants comparative analysis in their dashboard and I dont want them to revert to a QlikView paradigm for this.

Thanks

**Comment by PaulScotchford** [comment]
Sorry closed by accident.

**Comment by konne** [comment]
Hi @PaulScotchford,

please download from here: https://m.sense2go.net/extension-package or you have to compile the project, this is written direct on the Startpage.
I close that issue.

bye Konrad
