### ISSUE TITLE
Problem in the installation

### ISSUE THREAD

**Issue by Jonnnnnnnnnnnnnnnny** [q2g/q2g-ext-alternatestates#24]
Hey guys,

i´m wokring with the qlik Sense version 11 november 2017 11.24.4. Ich downloaded the zip file unzipped it and copied it into Qlik/Sense/extensions.

When I know run my Qlik Sense and choose the alternate state extension - I can add it into the sheet but when I want to add a new state my qlik sense gets me the following issue und shuts down:

Qlik has stopped working and must be shut down.

Does anyone has a solution for this problem?

Greetings Jonny

**Comment by konne** [comment]
Hi,

first, if you need support you can buy them from akquinet
second, it should work, we have tested with the same version
did you used that link to download the zip? https://m.sense2go.net/extension-package
Please add a screenshot / small screenrecording / browser debug info.
bye Konrad
